// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/06       [395270]
Creator        : mfloris
Date           : Sat Mar 18 16:02:06 2017
Host           : Linux lcgapp-slc6-x86-64-21.cern.ch 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 08:22:04 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /eos/user/m/mfloris/IML/IMLWorkshop2017-Challenge/Examples/TMVA
Training events: 18000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "10" [Number of grid points in variable range used in finding optimal cut in node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
jetPt                         jetPt                         jetPt                         jetPt                                                           'F'    [100.002243042,129.999359131]
jetEta                        jetEta                        jetEta                        jetEta                                                          'F'    [-4.10374307632,4.403175354]
jetPhi                        jetPhi                        jetPhi                        jetPhi                                                          'F'    [-3.14092493057,3.14155697823]
jetMass                       jetMass                       jetMass                       jetMass                                                         'F'    [1.03484714031,33.6880455017]
ntracks                       ntracks                       ntracks                       ntracks                                                         'F'    [0,37]
ntowers                       ntowers                       ntowers                       ntowers                                                         'F'    [0,61]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "jetPt", "jetEta", "jetPhi", "jetMass", "ntracks", "ntowers" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.386493452185001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7.51142, 1, 1, 0.729285,-99) , 
NN(
0, 
0, 
-1, 22.1818, 1, -1, 0.346115,-99) , 
3, 9.94026, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.25382);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496225,-99) , 
4, 6.72727, 1, 0, 0.617742,-99) , 
NN(
0, 
0, 
-1, 21, 1, -1, 0.370468,-99) , 
5, 16.6364, 1, 0, 0.5202,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.191666);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 12, 1, 1, 0.580958,-99) , 
NN(
0, 
0, 
-1, 2.36364, 1, -1, 0.339795,-99) , 
5, 22.1818, 1, 0, 0.539209,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.190904);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377487,-99) , 
4, 13.4545, 1, 0, 0.613252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37661,-99) , 
4, 3, 1, 0, 0.450736,-99) , 
5, 11.0909, 1, 0, 0.508125,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0964745);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.72727, 1, 1, 0.678999,-99) , 
NN(
0, 
0, 
-1, 27.7273, 1, -1, 0.469213,-99) , 
3, 6.97179, 1, 0, 0.493702,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.148401);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425598,-99) , 
4, 13.4545, 1, 0, 0.562569,-99) , 
NN(
0, 
0, 
-1, 29, 1, -1, 0.436053,-99) , 
5, 16.6364, 1, 0, 0.512232,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0636048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7.36364, 1, 1, 0.52245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343336,-99) , 
5, 27.7273, 1, 0, 0.510025,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0834935);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8, 1, 1, 0.554662,-99) , 
NN(
0, 
0, 
-1, 6, 1, -1, 0.465276,-99) , 
5, 11.0909, 1, 0, 0.496327,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0401014);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.72727, 1, 1, 0.600801,-99) , 
NN(
0, 
0, 
-1, 27.7273, 1, -1, 0.49023,-99) , 
3, 6.97179, 1, 0, 0.502704,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0517964);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 7.36364, 1, 1, 0.5195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386686,-99) , 
5, 27.7273, 1, 0, 0.510475,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0366637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 8.72727, 1, 1, 0.57857,-99) , 
NN(
0, 
0, 
-1, 27.7273, 1, -1, 0.48928,-99) , 
3, 6.97179, 1, 0, 0.499287,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0377544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499975,-99) , 
5, 7.36364, 1, 0, 0.513528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407863,-99) , 
5, 27.7273, 1, 0, 0.506402,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0839654);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415571,-99) , 
5, 27.7273, 1, 0, 0.524353,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406073,-99) , 
5, 7.27273, 1, 0, 0.449455,-99) , 
4, 10.0909, 1, 0, 0.512907,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0821976);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439756,-99) , 
5, 27.7273, 1, 0, 0.521044,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446362,-99) , 
5, 8.18182, 1, 0, 0.4757,-99) , 
4, 3.36364, 1, 0, 0.498675,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0276986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495507,-99) , 
5, 5.54545, 1, 0, 0.500112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425234,-99) , 
4, 13.4545, 1, 0, 0.494043,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0397613);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473841,-99) , 
5, 22.1818, 1, 0, 0.506076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432018,-99) , 
4, 13.4545, 1, 0, 0.500084,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0273024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461938,-99) , 
1, -1.78367, 0, 0, 0.499768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441799,-99) , 
4, 13.4545, 1, 0, 0.495087,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0179945);
  fForest.push_back( 
NN(
0, 
0, 
-1, 13.4545, 1, -1, 0.491004,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0207707);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456657,-99) , 
1, 2.08311, 1, 0, 0.499227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452998,-99) , 
4, 13.4545, 1, 0, 0.495502,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0272021);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496596,-99) , 
5, 8.72727, 1, 0, 0.523564,-99) , 
NN(
0, 
0, 
-1, 3.36364, 1, -1, 0.488074,-99) , 
3, 6.97179, 1, 0, 0.49202,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0349321);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464339,-99) , 
1, 1.59111, 1, 0, 0.502162,-99) , 
NN(
0, 
0, 
-1, -2.41644, 0, -1, 0.471517,-99) , 
1, -1.78367, 0, 0, 0.498062,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0394981);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472428,-99) , 
0, 121.816, 1, 0, 0.504629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469677,-99) , 
5, 8.18182, 1, 0, 0.484167,-99) , 
4, 3.36364, 1, 0, 0.494546,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0377954);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459332,-99) , 
4, 13.4545, 1, 0, 0.501028,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437847,-99) , 
3, 8.32099, 1, 0, 0.480412,-99) , 
3, 9.94026, 0, 0, 0.493035,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.024085);
  fForest.push_back( 
NN(
0, 
0, 
-1, 22.1818, 1, -1, 0.48796,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0240915);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449853,-99) , 
5, 20, 1, 0, 0.497717,-99) , 
NN(
0, 
0, 
-1, 16.4266, 0, -1, 0.475749,-99) , 
5, 22.1818, 1, 0, 0.493979,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0403237);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48175,-99) , 
4, 6.72727, 1, 0, 0.498535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456044,-99) , 
3, 7.51142, 1, 0, 0.479562,-99) , 
3, 9.94026, 0, 0, 0.491182,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0254457);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517934,-99) , 
NN(
0, 
0, 
-1, 19.6364, 1, -1, 0.487775,-99) , 
3, 18.8457, 0, 0, 0.490393,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0234496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456757,-99) , 
5, 20, 1, 0, 0.499353,-99) , 
NN(
0, 
0, 
-1, -0.33452, 0, -1, 0.477587,-99) , 
5, 22.1818, 1, 0, 0.495648,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0257064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491265,-99) , 
2, -0.856347, 1, 0, 0.499263,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.482903,-99) , 
3, 9.94026, 0, 0, 0.492925,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.025894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4907,-99) , 
5, 13.6364, 1, 0, 0.504527,-99) , 
NN(
0, 
0, 
-1, -0.989397, 0, -1, 0.488369,-99) , 
0, 110.91, 1, 0, 0.496389,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0234899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486866,-99) , 
4, 10.0909, 1, 0, 0.505451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447227,-99) , 
3, 9.13056, 1, 0, 0.490872,-99) , 
3, 9.94026, 0, 0, 0.499805,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0189267);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474123,-99) , 
5, 27.7273, 1, 0, 0.501937,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.487497,-99) , 
3, 9.94026, 0, 0, 0.496345,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0297163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490258,-99) , 
5, 9.09091, 1, 0, 0.50008,-99) , 
NN(
0, 
0, 
-1, 119.065, 1, -1, 0.485015,-99) , 
1, -1.01032, 0, 0, 0.495905,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0224837);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522108,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475156,-99) , 
5, 19.6364, 1, 0, 0.498672,-99) , 
3, 18.8457, 0, 0, 0.50071,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0339813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484864,-99) , 
5, 21, 1, 0, 0.505566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437196,-99) , 
5, 14.5455, 1, 0, 0.492098,-99) , 
5, 16.6364, 0, 0, 0.497471,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0262563);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496315,-99) , 
1, 1.17317, 0, 0, 0.506958,-99) , 
NN(
0, 
0, 
-1, 1.32296, 1, -1, 0.486408,-99) , 
5, 16.6364, 0, 0, 0.494604,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0319428);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475031,-99) , 
4, 5.27273, 1, 0, 0.510129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450709,-99) , 
1, 1.32296, 1, 0, 0.49297,-99) , 
5, 16.6364, 0, 0, 0.499813,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0268964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49065,-99) , 
5, 21, 1, 0, 0.5052,-99) , 
NN(
0, 
0, 
-1, 14.5455, 1, -1, 0.488306,-99) , 
5, 16.6364, 0, 0, 0.495043,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0179844);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489356,-99) , 
4, 3.36364, 1, 0, 0.497147,-99) , 
3, 18.8457, 0, 0, 0.499525,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0230042);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483971,-99) , 
4, 13.4545, 1, 0, 0.504625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470461,-99) , 
0, 110.91, 1, 0, 0.490167,-99) , 
3, 9.94026, 0, 0, 0.499028,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0192559);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484121,-99) , 
5, 14.7273, 1, 0, 0.494155,-99) , 
3, 18.8457, 0, 0, 0.496067,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0162002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482682,-99) , 
0, 102.731, 0, 0, 0.50059,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.487088,-99) , 
3, 9.94026, 0, 0, 0.495363,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0175073);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494979,-99) , 
3, 8.46708, 1, 0, 0.503182,-99) , 
NN(
0, 
0, 
-1, -0.96374, 0, -1, 0.491882,-99) , 
0, 105.456, 1, 0, 0.495089,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0115084);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496357,-99) , 
5, 16.6364, 0, 0, 0.500285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482638,-99) , 
2, 2.57042, 1, 0, 0.498756,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.019826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456361,-99) , 
1, 2.43471, 1, 0, 0.502547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457984,-99) , 
0, 119.065, 1, 0, 0.491667,-99) , 
1, -1.01032, 0, 0, 0.499528,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0131259);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494224,-99) , 
2, 1.01259, 0, 0, 0.497112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481676,-99) , 
2, 2.57042, 1, 0, 0.495775,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0148304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491332,-99) , 
5, 14.7273, 1, 0, 0.504261,-99) , 
NN(
0, 
0, 
-1, -1.01032, 0, -1, 0.494735,-99) , 
2, -1.42752, 1, 0, 0.497387,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0177975);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496294,-99) , 
5, 9.09091, 1, 0, 0.502593,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456587,-99) , 
1, -2.41645, 0, 0, 0.493497,-99) , 
1, -1.01032, 0, 0, 0.500069,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0189431);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467961,-99) , 
1, 2.43471, 1, 0, 0.504866,-99) , 
NN(
0, 
0, 
-1, 119.065, 1, -1, 0.490813,-99) , 
1, -1.01032, 0, 0, 0.500967,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0177815);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49647,-99) , 
1, 1.17317, 0, 0, 0.504705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462459,-99) , 
5, 14.5455, 1, 0, 0.495816,-99) , 
5, 16.6364, 0, 0, 0.499362,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0180337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495773,-99) , 
5, 21, 1, 0, 0.506855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465492,-99) , 
1, 1.32296, 1, 0, 0.492835,-99) , 
5, 16.6364, 0, 0, 0.498428,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0221382);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485957,-99) , 
4, 5.27273, 1, 0, 0.507597,-99) , 
NN(
0, 
0, 
-1, 14.5455, 1, -1, 0.4902,-99) , 
5, 16.6364, 0, 0, 0.49714,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0116214);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496056,-99) , 
5, 4.90909, 1, 0, 0.497592,-99) , 
3, 18.8457, 0, 0, 0.499104,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0160633);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499876,-99) , 
3, 17.2711, 0, 0, 0.504614,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482348,-99) , 
5, 8, 1, 0, 0.494569,-99) , 
5, 11.0909, 0, 0, 0.50114,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0161405);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 105.458, 1, 1, 0.507234,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473183,-99) , 
1, -0.987199, 0, 0, 0.494997,-99) , 
5, 11.0909, 0, 0, 0.503002,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0122417);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498248,-99) , 
0, 105.458, 1, 0, 0.503199,-99) , 
NN(
0, 
0, 
-1, 1.32296, 1, -1, 0.493166,-99) , 
5, 11.0909, 0, 0, 0.49973,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0215899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493784,-99) , 
4, 1.18182, 1, 0, 0.50296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487247,-99) , 
4, 13.4545, 1, 0, 0.501692,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0165134);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.08311, 0, 1, 0.50655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469766,-99) , 
3, 9.13056, 1, 0, 0.498099,-99) , 
3, 9.94026, 0, 0, 0.503283,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.00881888);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503749,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496434,-99) , 
1, 0.536394, 1, 0, 0.500965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48789,-99) , 
2, 2.57042, 1, 0, 0.499833,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.00890023);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499507,-99) , 
1, 2.08311, 0, 0, 0.502121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473521,-99) , 
3, 9.13056, 1, 0, 0.495454,-99) , 
3, 9.94026, 0, 0, 0.499543,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0093643);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.08311, 0, 1, 0.503962,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.494175,-99) , 
3, 9.94026, 0, 0, 0.500178,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0130778);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495553,-99) , 
4, 1.18182, 1, 0, 0.500623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48852,-99) , 
4, 13.4545, 1, 0, 0.499647,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0138181);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492129,-99) , 
5, 17.1818, 1, 0, 0.501618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486663,-99) , 
5, 27.7273, 1, 0, 0.500611,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.00755851);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.08311, 0, 1, 0.502752,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.494592,-99) , 
3, 9.94026, 0, 0, 0.499597,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.00815604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491125,-99) , 
2, 1.99929, 1, 0, 0.500183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487612,-99) , 
4, 13.4545, 1, 0, 0.499169,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0101706);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49694,-99) , 
3, 17.7019, 0, 0, 0.498935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486941,-99) , 
5, 27.7273, 1, 0, 0.498127,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00508528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499483,-99) , 
3, 17.7019, 0, 0, 0.501024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489482,-99) , 
5, 27.7273, 1, 0, 0.500247,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00815514);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498737,-99) , 
4, 1.18182, 1, 0, 0.50215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491693,-99) , 
4, 13.4545, 1, 0, 0.501307,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0178916);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492956,-99) , 
4, 9.72727, 1, 0, 0.506814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479541,-99) , 
4, 4.36364, 1, 0, 0.499622,-99) , 
4, 6.72727, 0, 0, 0.501908,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0209203);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49483,-99) , 
2, 0.28586, 1, 0, 0.505474,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484601,-99) , 
4, 0.272727, 1, 0, 0.494796,-99) , 
4, 3.36364, 0, 0, 0.50006,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.00994536);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.09091, 1, 1, 0.504941,-99) , 
NN(
0, 
0, 
-1, 14.5934, 1, -1, 0.494997,-99) , 
4, 3.36364, 0, 0, 0.4999,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0140077);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.27287, 1, 1, 0.504769,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492232,-99) , 
0, 105.46, 1, 0, 0.497134,-99) , 
2, 0.857018, 0, 0, 0.499934,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0112817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4926,-99) , 
5, 17.1818, 1, 0, 0.500552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486708,-99) , 
5, 27.7273, 1, 0, 0.499619,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0177485);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470936,-99) , 
5, 29, 1, 0, 0.503119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464995,-99) , 
5, 14.5455, 1, 0, 0.495921,-99) , 
5, 16.6364, 0, 0, 0.498791,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0165546);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486903,-99) , 
0, 108.185, 0, 0, 0.498544,-99) , 
NN(
0, 
0, 
-1, 9.13056, 1, -1, 0.491223,-99) , 
3, 9.94026, 0, 0, 0.495713,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.00954778);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492724,-99) , 
4, 2.36364, 0, 0, 0.497314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488456,-99) , 
4, 13.4545, 1, 0, 0.4966,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0158709);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496077,-99) , 
0, 124.546, 0, 0, 0.498701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482367,-99) , 
5, 8, 1, 0, 0.492826,-99) , 
5, 11.0909, 0, 0, 0.496668,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00976745);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498681,-99) , 
3, 17.2711, 0, 0, 0.501716,-99) , 
NN(
0, 
0, 
-1, 1.32296, 1, -1, 0.493248,-99) , 
5, 11.0909, 0, 0, 0.498785,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0089331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.84221, 1, 1, 0.503309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47358,-99) , 
1, 1.32296, 1, 0, 0.495689,-99) , 
5, 11.0909, 0, 0, 0.500673,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00949195);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498576,-99) , 
1, -1.84221, 1, 0, 0.501076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476926,-99) , 
1, -0.987199, 0, 0, 0.494383,-99) , 
5, 11.0909, 0, 0, 0.49876,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0105303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498853,-99) , 
0, 105.458, 1, 0, 0.502843,-99) , 
NN(
0, 
0, 
-1, 1.32296, 1, -1, 0.493305,-99) , 
5, 11.0909, 0, 0, 0.499543,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0134251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495597,-99) , 
5, 20.9091, 1, 0, 0.504032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476066,-99) , 
1, 1.32296, 1, 0, 0.495938,-99) , 
5, 11.0909, 0, 0, 0.501231,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0123945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49846,-99) , 
1, 1.17317, 0, 0, 0.505609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472877,-99) , 
5, 14.5455, 1, 0, 0.49614,-99) , 
5, 16.6364, 0, 0, 0.499915,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0128105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 10.2657, 1, 1, 0.507108,-99) , 
NN(
0, 
0, 
-1, 124.544, 1, -1, 0.494061,-99) , 
5, 16.6364, 0, 0, 0.499263,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.010198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 17.2711, 0, 1, 0.502999,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48377,-99) , 
2, 0.285902, 1, 0, 0.494078,-99) , 
5, 11.0909, 0, 0, 0.499912,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00930148);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497928,-99) , 
3, 17.2711, 0, 0, 0.50045,-99) , 
NN(
0, 
0, 
-1, -0.987199, 0, -1, 0.493882,-99) , 
5, 11.0909, 0, 0, 0.498177,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0102123);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486988,-99) , 
0, 124.544, 1, 0, 0.501622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480001,-99) , 
4, 6.72727, 1, 0, 0.492336,-99) , 
3, 15.8772, 1, 0, 0.499974,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.011433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493272,-99) , 
5, 16, 1, 0, 0.499603,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48301,-99) , 
3, 19.1169, 0, 0, 0.491862,-99) , 
3, 15.8772, 1, 0, 0.49823,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.00999337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49859,-99) , 
0, 124.546, 0, 0, 0.50083,-99) , 
NN(
0, 
0, 
-1, -0.987199, 0, -1, 0.491817,-99) , 
5, 11.0909, 0, 0, 0.497711,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00759409);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.84221, 1, 1, 0.502728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478941,-99) , 
1, -0.987199, 0, 0, 0.494315,-99) , 
5, 11.0909, 0, 0, 0.499817,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0116026);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497171,-99) , 
3, 10.2657, 1, 0, 0.502764,-99) , 
NN(
0, 
0, 
-1, 14.5455, 1, -1, 0.495301,-99) , 
5, 16.6364, 0, 0, 0.498277,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.00884347);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.84221, 1, 1, 0.503131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485422,-99) , 
1, 0.552908, 1, 0, 0.496354,-99) , 
5, 11.0909, 0, 0, 0.500786,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.00782219);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498304,-99) , 
5, 8, 1, 0, 0.50045,-99) , 
NN(
0, 
0, 
-1, 119.095, 1, -1, 0.492992,-99) , 
3, 15.8772, 1, 0, 0.499126,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00790319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.84221, 1, 1, 0.502876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481811,-99) , 
1, -0.987199, 0, 0, 0.49605,-99) , 
5, 11.0909, 0, 0, 0.500514,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0119564);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475821,-99) , 
5, 29, 1, 0, 0.502451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477525,-99) , 
5, 14.5455, 1, 0, 0.496564,-99) , 
5, 16.6364, 0, 0, 0.498912,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0108176);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49724,-99) , 
1, -1.84221, 1, 0, 0.49931,-99) , 
NN(
0, 
0, 
-1, 11.0937, 1, -1, 0.492165,-99) , 
5, 11.0909, 0, 0, 0.496838,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0081437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498541,-99) , 
1, 1.17317, 0, 0, 0.501323,-99) , 
NN(
0, 
0, 
-1, 11.0937, 1, -1, 0.494869,-99) , 
5, 11.0909, 0, 0, 0.49909,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0116229);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497931,-99) , 
5, 16.6364, 0, 0, 0.501565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476474,-99) , 
3, 10.5975, 1, 0, 0.494211,-99) , 
0, 102.729, 0, 0, 0.500459,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0125759);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49495,-99) , 
5, 16, 1, 0, 0.502337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480897,-99) , 
0, 119.095, 1, 0, 0.49419,-99) , 
3, 15.8772, 1, 0, 0.500892,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.00965974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498372,-99) , 
3, 11.8287, 0, 0, 0.501584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484684,-99) , 
2, -0.285367, 1, 0, 0.49312,-99) , 
3, 15.8772, 1, 0, 0.500083,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
